### ISSUE TITLE
video thumbnails

### ISSUE THREAD

**Issue by exentric-gr** [bobopinna/moodle-repository_personalyoutube#1]
Has anyone figured out how to get the thumbnail for the video, looks like the url of the image has changed ?
https://i9.ytimg.com/vi/
https://img.youtube.com/vi/

**Comment by bobopinna** [comment]
Your question could be a little off topic.
Thumbnails are not managed by Personal YouTube plugin.
They are defined and called by VideoJS.

It seems that private video thumbnails are now hidden, finally.
You can try with a not listed or a public video.

HTH,
Roberto
